// <auto-generated />
using System;
using LifeOS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeOS.Api.Migrations
{
    [DbContext(typeof(LifeOsDbContext))]
    partial class LifeOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.Api.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeIcon")
                        .HasColumnType("text")
                        .HasColumnName("badge_icon");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<string>("UnlockCondition")
                        .HasColumnType("text")
                        .HasColumnName("unlock_condition");

                    b.Property<bool>("Unlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("unlocked");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<int>("XpReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_achievements");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_achievements_profile_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_achievements_tree_id");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandArchetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffinityPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("affinity_pct");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_brand_archetypes");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_brand_archetypes_profile_id");

                    b.ToTable("brand_archetypes");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandPillar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Thesis")
                        .HasColumnType("text")
                        .HasColumnName("thesis");

                    b.Property<int>("WeightPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("weight_pct");

                    b.HasKey("Id")
                        .HasName("pk_brand_pillars");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_brand_pillars_profile_id");

                    b.ToTable("brand_pillars");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codename");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("GlobalLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("global_level");

                    b.Property<string>("MissionStatement")
                        .HasColumnType("text")
                        .HasColumnName("mission_statement");

                    b.Property<string>("OriginStory")
                        .HasColumnType("text")
                        .HasColumnName("origin_story");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("bronze")
                        .HasColumnName("tier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Aspiring Engineer")
                        .HasColumnName("title");

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_xp");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_brand_profiles");

                    b.ToTable("brand_profiles");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("base_value");

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_value");

                    b.Property<int>("MaxValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("max_value");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat_name");

                    b.HasKey("Id")
                        .HasName("pk_brand_stats");

                    b.HasIndex("ProfileId", "StatName")
                        .IsUnique();

                    b.ToTable("brand_stats");
                });

            modelBuilder.Entity("LifeOS.Api.Models.ContentQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Draft")
                        .HasColumnType("text")
                        .HasColumnName("draft");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid?>("PillarId")
                        .HasColumnType("uuid")
                        .HasColumnName("pillar_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateOnly?>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("idea")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("XpOnPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("xp_on_publish");

                    b.HasKey("Id")
                        .HasName("pk_content_queue");

                    b.HasIndex("PillarId")
                        .HasDatabaseName("ix_content_queue_pillar_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_content_queue_platform_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_content_queue_tree_id");

                    b.ToTable("content_queue");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Finance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CurrentRal")
                        .HasColumnType("numeric")
                        .HasColumnName("current_ral");

                    b.Property<decimal>("MonthlyBurn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthly_burn");

                    b.Property<decimal>("Savings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("savings");

                    b.Property<decimal?>("TargetDailyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("target_daily_rate");

                    b.Property<decimal?>("TargetRal")
                        .HasColumnType("numeric")
                        .HasColumnName("target_ral");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_finances");

                    b.ToTable("finances");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<int>("ProgressPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_pct");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("not_started")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_goals_domain_id");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("daily")
                        .HasColumnName("frequency");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("StreakBest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("streak_best");

                    b.Property<int>("StreakCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("streak_current");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_habits_domain_id");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("ix_habits_goal_id");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("LifeOS.Api.Models.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("completed");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<DateOnly>("LoggedDate")
                        .HasColumnType("date")
                        .HasColumnName("logged_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_habit_logs");

                    b.HasIndex("HabitId", "LoggedDate")
                        .IsUnique();

                    b.ToTable("habit_logs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.IncomeStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FinanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_id");

                    b.Property<string>("Frequency")
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_income_streams");

                    b.HasIndex("FinanceId")
                        .HasDatabaseName("ix_income_streams_finance_id");

                    b.ToTable("income_streams");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phase_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("numeric")
                        .HasColumnName("salary");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("WorkMode")
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_jobs_phase_id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Mood")
                        .HasColumnType("text")
                        .HasColumnName("mood");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_journal_entries_domain_id");

                    b.ToTable("journal_entries");
                });

            modelBuilder.Entity("LifeOS.Api.Models.LifeDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_life_domains");

                    b.ToTable("life_domains");
                });

            modelBuilder.Entity("LifeOS.Api.Models.LifePhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EnergyLevel")
                        .HasColumnType("text")
                        .HasColumnName("energy_level");

                    b.Property<string>("LessonLearned")
                        .HasColumnType("text")
                        .HasColumnName("lesson_learned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_life_phases");

                    b.ToTable("life_phases");
                });

            modelBuilder.Entity("LifeOS.Api.Models.MentalState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Antidote")
                        .HasColumnType("text")
                        .HasColumnName("antidote");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern_name");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phase_id");

                    b.Property<string>("TriggerDesc")
                        .HasColumnType("text")
                        .HasColumnName("trigger_desc");

                    b.Property<string>("Valence")
                        .HasColumnType("text")
                        .HasColumnName("valence");

                    b.HasKey("Id")
                        .HasName("pk_mental_states");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_mental_states_phase_id");

                    b.ToTable("mental_states");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("ix_milestones_goal_id");

                    b.ToTable("milestones");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Handle")
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_platforms_profile_id");

                    b.ToTable("platforms");
                });

            modelBuilder.Entity("LifeOS.Api.Models.PlatformMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EngagementRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("engagement_rate");

                    b.Property<int>("Followers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("followers");

                    b.Property<int>("Impressions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("impressions");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<int>("PostsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("posts_count");

                    b.Property<int>("ProfileViews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("profile_views");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.HasKey("Id")
                        .HasName("pk_platform_metrics");

                    b.HasIndex("PlatformId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("platform_metrics");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("text")
                        .HasColumnName("current_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoleInStory")
                        .HasColumnType("text")
                        .HasColumnName("role_in_story");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.ToTable("relationships");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CertDate")
                        .HasColumnType("date")
                        .HasColumnName("cert_date");

                    b.Property<string>("CertName")
                        .HasColumnType("text")
                        .HasColumnName("cert_name");

                    b.Property<bool>("Certified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("certified");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_skills_job_id");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LevelRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<bool>("Unlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("unlocked");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<int>("XpReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_skill_nodes");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_skill_nodes_tree_id");

                    b.ToTable("skill_nodes");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("TreeLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("tree_level");

                    b.Property<int>("TreeXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tree_xp");

                    b.Property<int>("XpToNext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("xp_to_next");

                    b.HasKey("Id")
                        .HasName("pk_skill_trees");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_skill_trees_domain_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_skill_trees_profile_id");

                    b.ToTable("skill_trees");
                });

            modelBuilder.Entity("LifeOS.Api.Models.TurningPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("Impact")
                        .HasColumnType("text")
                        .HasColumnName("impact");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phase_id");

                    b.Property<string>("Reflection")
                        .HasColumnType("text")
                        .HasColumnName("reflection");

                    b.HasKey("Id")
                        .HasName("pk_turning_points");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_turning_points_phase_id");

                    b.ToTable("turning_points");
                });

            modelBuilder.Entity("LifeOS.Api.Models.XpLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("evidence_url");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer")
                        .HasColumnName("xp_earned");

                    b.HasKey("Id")
                        .HasName("pk_xp_logs");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_xp_logs_node_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_xp_logs_platform_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_xp_logs_tree_id");

                    b.ToTable("xp_logs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Achievement", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("Achievements")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_achievements_brand_profiles_profile_id");

                    b.HasOne("LifeOS.Api.Models.SkillTree", "Tree")
                        .WithMany("Achievements")
                        .HasForeignKey("TreeId")
                        .HasConstraintName("fk_achievements_skill_trees_tree_id");

                    b.Navigation("Profile");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandArchetype", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("Archetypes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_archetypes_brand_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandPillar", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("Pillars")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_pillars_brand_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandStat", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("Stats")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_stats_brand_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeOS.Api.Models.ContentQueue", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandPillar", "Pillar")
                        .WithMany("ContentItems")
                        .HasForeignKey("PillarId")
                        .HasConstraintName("fk_content_queue_brand_pillars_pillar_id");

                    b.HasOne("LifeOS.Api.Models.Platform", "Platform")
                        .WithMany("ContentItems")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_queue_platforms_platform_id");

                    b.HasOne("LifeOS.Api.Models.SkillTree", "Tree")
                        .WithMany("ContentItems")
                        .HasForeignKey("TreeId")
                        .HasConstraintName("fk_content_queue_skill_trees_tree_id");

                    b.Navigation("Pillar");

                    b.Navigation("Platform");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Goal", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifeDomain", "Domain")
                        .WithMany("Goals")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_life_domains_domain_id");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Habit", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifeDomain", "Domain")
                        .WithMany("Habits")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habits_life_domains_domain_id");

                    b.HasOne("LifeOS.Api.Models.Goal", "Goal")
                        .WithMany("Habits")
                        .HasForeignKey("GoalId")
                        .HasConstraintName("fk_habits_goals_goal_id");

                    b.Navigation("Domain");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("LifeOS.Api.Models.HabitLog", b =>
                {
                    b.HasOne("LifeOS.Api.Models.Habit", "Habit")
                        .WithMany("HabitLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_logs_habits_habit_id");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("LifeOS.Api.Models.IncomeStream", b =>
                {
                    b.HasOne("LifeOS.Api.Models.Finance", "Finance")
                        .WithMany("IncomeStreams")
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_income_streams_finances_finance_id");

                    b.Navigation("Finance");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Job", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifePhase", "Phase")
                        .WithMany("Jobs")
                        .HasForeignKey("PhaseId")
                        .HasConstraintName("fk_jobs_life_phases_phase_id");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("LifeOS.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifeDomain", "Domain")
                        .WithMany("JournalEntries")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("fk_journal_entries_life_domains_domain_id");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("LifeOS.Api.Models.MentalState", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifePhase", "Phase")
                        .WithMany("MentalStates")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mental_states_life_phases_phase_id");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Milestone", b =>
                {
                    b.HasOne("LifeOS.Api.Models.Goal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Platform", b =>
                {
                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("Platforms")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platforms_brand_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeOS.Api.Models.PlatformMetrics", b =>
                {
                    b.HasOne("LifeOS.Api.Models.Platform", "Platform")
                        .WithMany("Metrics")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_metrics_platforms_platform_id");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Skill", b =>
                {
                    b.HasOne("LifeOS.Api.Models.Job", "Job")
                        .WithMany("Skills")
                        .HasForeignKey("JobId")
                        .HasConstraintName("fk_skills_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillNode", b =>
                {
                    b.HasOne("LifeOS.Api.Models.SkillTree", "Tree")
                        .WithMany("Nodes")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_nodes_skill_trees_tree_id");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillTree", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifeDomain", "Domain")
                        .WithMany("SkillTrees")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("fk_skill_trees_life_domains_domain_id");

                    b.HasOne("LifeOS.Api.Models.BrandProfile", "Profile")
                        .WithMany("SkillTrees")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_trees_brand_profiles_profile_id");

                    b.Navigation("Domain");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LifeOS.Api.Models.TurningPoint", b =>
                {
                    b.HasOne("LifeOS.Api.Models.LifePhase", "Phase")
                        .WithMany("TurningPoints")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_turning_points_life_phases_phase_id");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("LifeOS.Api.Models.XpLog", b =>
                {
                    b.HasOne("LifeOS.Api.Models.SkillNode", "Node")
                        .WithMany("XpLogs")
                        .HasForeignKey("NodeId")
                        .HasConstraintName("fk_xp_logs_skill_nodes_node_id");

                    b.HasOne("LifeOS.Api.Models.Platform", "Platform")
                        .WithMany("XpLogs")
                        .HasForeignKey("PlatformId")
                        .HasConstraintName("fk_xp_logs_platforms_platform_id");

                    b.HasOne("LifeOS.Api.Models.SkillTree", "Tree")
                        .WithMany("XpLogs")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_xp_logs_skill_trees_tree_id");

                    b.Navigation("Node");

                    b.Navigation("Platform");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandPillar", b =>
                {
                    b.Navigation("ContentItems");
                });

            modelBuilder.Entity("LifeOS.Api.Models.BrandProfile", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Archetypes");

                    b.Navigation("Pillars");

                    b.Navigation("Platforms");

                    b.Navigation("SkillTrees");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Finance", b =>
                {
                    b.Navigation("IncomeStreams");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Goal", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Habit", b =>
                {
                    b.Navigation("HabitLogs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Job", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LifeOS.Api.Models.LifeDomain", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Habits");

                    b.Navigation("JournalEntries");

                    b.Navigation("SkillTrees");
                });

            modelBuilder.Entity("LifeOS.Api.Models.LifePhase", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("MentalStates");

                    b.Navigation("TurningPoints");
                });

            modelBuilder.Entity("LifeOS.Api.Models.Platform", b =>
                {
                    b.Navigation("ContentItems");

                    b.Navigation("Metrics");

                    b.Navigation("XpLogs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillNode", b =>
                {
                    b.Navigation("XpLogs");
                });

            modelBuilder.Entity("LifeOS.Api.Models.SkillTree", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ContentItems");

                    b.Navigation("Nodes");

                    b.Navigation("XpLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
